# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrebidDemo' do
  

  # Pods for PrebidDemo

  pod 'Google-Mobile-Ads-SDK'

  pod 'mopub-ios-sdk'

end
