# Ordered by output of `jazzy — help config`
output: docs
clean: true
xcodebuild_arguments:
- -workspace
- PrebidMobile.xcworkspace
- -scheme
- Lib-PrebidMobile
- CODE_SIGNING_ALLOWED = NO
author: Prebid
readme: README_API_DOC.md
exclude:
  - PrebidMobile/Swift/Addendum/*
  - PrebidMobile/Swift/AdUnits/BannerBasedAdUnitProtocol.swift
  - PrebidMobile/Swift/AdUnits/VideoBasedAdUnitProtocol.swift
  - PrebidMobile/Swift/AdUnits/Utils.swift
  - PrebidMobile/Swift/CacheManagement/*
  - PrebidMobile/Swift/ConfigurationAndTargeting/AgeUtils.swift
  - PrebidMobile/Swift/ConfigurationAndTargeting/ClickbrowserType.swift
  - PrebidMobile/Swift/ConfigurationAndTargeting/PrebidGAMVersionChecker.swift
  - PrebidMobile/Swift/ConfigurationAndTargeting/PrebidSDKInitializer.swift
  - PrebidMobile/Swift/ConfigurationAndTargeting/PrebidServerStatusRequester.swift
  - PrebidMobile/Swift/ConfigurationAndTargeting/UserConsentDataManager.swift
  - PrebidMobile/Swift/Constants.swift
  - PrebidMobile/Swift/Dispatcher.swift
  - PrebidMobile/Swift/ImageHelper.swift
  - PrebidMobile/Swift/JSONConvertible.swift
  - PrebidMobile/Swift/JsonDecodable.swift
  - PrebidMobile/Swift/Factory.swift
  - PrebidMobile/Swift/SwiftMigrationHelper.swift
  - PrebidMobile/Swift/Logging/*
  - PrebidMobile/Swift/StorageUtils.swift
  - PrebidMobile/Swift/Tracker*
  - PrebidMobile/Swift/UIViewExtension.swift
  - PrebidMobile/Swift/Utils/*
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/AdConfiguration.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/AdViewButtonDecorator.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/HiddenWebViewManager.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/WebView.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/WebView.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/WebView.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/Modals/*
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/AdViewManagerDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/InterstitialDisplayProperties.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/AdView/InterstitialLayout.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AdTypes/Video/Vast/VastTrackingEvents.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Assets/PrebidImagesRepository.swift
  - PrebidMobile/Swift/PrebidMobileRendering/AutoRefreshCountConfig.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Impression*
  - PrebidMobile/Swift/PrebidMobileRendering/Networking*
  - PrebidMobile/Swift/PrebidMobileRendering/ORTB/*
  - PrebidMobile/Swift/PrebidMobileRendering/Models/*
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/AdLoading/AdLoadFlowControllerDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/AdLoading/BannerAdLoaderDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/BannerEventInteractionDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/BannerEventLoadingDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/InterstitialEventInteractionDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/InterstitialEventLoadingDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/RewardedEventInteractionDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/RewardedEventLoadingDelegate.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/BaseInterstitialAdUnitProtocol.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/GAM/InterstitialEventHandlerProtocol.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/MediationAPI/MediationUtils.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/MediationAPI/MediationNativeUtils.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/MediationAPI/MediationConstants.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/MediationAPI/MediationBidInfoWrapper.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/PBMStandaloneSDK/DemandResponseInfo.swift
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/Integrations/PBMStandaloneSDK/EventHandlers/*
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/PBMCore/*
  - PrebidMobile/Swift/PrebidMobileRendering/Prebid/PBMCacheRenderers/*
  - PrebidMobile/Swift/PrebidMobileRendering/PrebidServerEventTracker.swift
  - PrebidMobile/Swift/PrebidMobileRendering/ServerEvent.swift
  - PrebidMobile/Swift/PrebidMobileRendering/ServerSideConfiguration/*
  - PrebidMobile/Swift/PrebidMobileRendering/Skadn*
  - PrebidMobile/Swift/PrebidMobileRendering/Utilities/*
  - PrebidMobile/Swift/PrebidMobileRendering/3dPartyWrappers/OpenMeasurement/*
theme: apple
