# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrebidMobileDemo' do
  pod 'Google-Mobile-Ads-SDK', '7.30.0'
  pod 'mopub-ios-sdk', '4.20.1'

end
