# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrebidDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrebidDemo
  pod 'Google-Mobile-Ads-SDK'
  pod 'mopub-ios-sdk'
  
  target 'PrebidDemoTests' do
      inherit! :search_paths
  end
end
