# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PrebidDemoObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for PrebidDemoObjectiveC
 use_frameworks!
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'mopub-ios-sdk'
  pod 'GoogleAds-IMA-iOS-SDK'
  pod 'PrebidMobile','~>1.12.1'
end

target 'PrebidDemoSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrebidDemoSwift
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'mopub-ios-sdk'
  pod 'GoogleAds-IMA-iOS-SDK'
  pod 'PrebidMobile','~>1.12.1'
end
