# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrebidValidator' do
    pod 'PrebidMobile'
    pod 'mopub-ios-sdk'
    pod 'Google-Mobile-Ads-SDK'
end

