
name: Full / Selective PrebidMobile Checks

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build PrebidMobile frameworks'
        type: boolean
        default: false
      unit_tests:
        description: 'Run Unit Tests'
        type: boolean
        default: false            
      smoke_ui_tests:
        description: 'Run Smoke UI Tests - Swift Demo App'
        type: boolean
        default: false
      integration_tests:
        description: 'Run Integration Tests'
        type: boolean
        default: false
      all:
        description: 'Run All PrebidMobile checks'
        type: boolean
        default: true

env:
  XCODE_VERSION: "16.4.0"

jobs:
  build:
    name: Build PrebidMobile Frameworks
    if: ${{ inputs.all || inputs.build }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: ${{ env.XCODE_VERSION }}
      - run: ./scripts/buildPrebidMobile.sh
      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: generated/log/prebid_mobile_build.log
          retention-days: 1

  unit_tests:
    name: Run All Unit Tests for Frameworks
    if: ${{ inputs.all || inputs.unit_tests }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: ${{ env.XCODE_VERSION }}
      - run: ./scripts/testPrebidMobile.sh --latest

  smoke_ui_tests:
    name: Run Smoke UI Tests - Swift Demo App
    if: ${{ inputs.all || inputs.smoke_ui_tests }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: ${{ env.XCODE_VERSION }}
      - run: ./scripts/testPrebidDemo.sh -ui -l

  integration_tests:
    name: Run Integration Tests - Swift Demo App
    if: ${{ inputs.all || inputs.integration_tests }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: ${{ env.XCODE_VERSION }}
      - run: ./scripts/testPrebidDemo.sh -l