# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'ios-sdk-v3'

project 'PrebidMobileDemoRendering/PrebidMobileDemoRendering/PrebidMobileDemoRendering.xcodeproj'

def mopub_pods
  pod 'mopub-ios-sdk'
end

def gma_pods
    pod 'Google-Mobile-Ads-SDK'
end

def event_handlers_project
  project 'EventHandlers/EventHandlers.xcodeproj'
  use_frameworks!
end

target 'PrebidMobileGAMEventHandlers' do
  event_handlers_project
  gma_pods
end

target 'PrebidMobileGAMEventHandlersTests' do
  event_handlers_project
  gma_pods
end

target 'PrebidMobileMoPubAdapters' do
  event_handlers_project
  mopub_pods
end


def internalTestApp_pods
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'xcode12'
  pod 'SVProgressHUD'
  mopub_pods
  gma_pods
end

target 'PrebidMobileDemoRendering' do
  use_frameworks!
  project 'PrebidMobileDemoRendering/PrebidMobileDemoRendering/PrebidMobileDemoRendering.xcodeproj'
  internalTestApp_pods
end

target 'OpenXMockServer' do
  use_frameworks!
  pod 'Alamofire', '4.9.1'
  pod 'RxSwift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
        end
    end
end
